version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - run:
        name: namet
        command: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global hub.protocol "https"
          mkdir -p ~/.config
          printf "github.com:\n- user: $GITHUB_LOGIN\n  oauth_token: $GITHUB_TOKEN\n  protocol: https\n" > ~/.config/hub
          printf "machine github.com\nlogin $GITHUB_LOGIN\npassword $GITHUB_TOKEN\n" > ~/.netrc
          hub fork

          ls -a



workflows:
  version: 2
  abas:
    jobs:
    - abasia
